version: '3'


services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    volumes:
      - /app/node_modules
      - .:/app  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app     
      # overiding the startup command of docker file
    command: ["npm","run","test"]  