version: 2.1
jobs: 
  build_container:
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Build the Docker image
          working-directory: .
          command: | 
            docker build -t bipen2001/docker-react -f Dockerfile.dev .  

      - run:
          name: run tests
          working-directory: .
          command: | 
            sudo docker run -e CI=True  bipen2001/docker-react npm run test -- --coverage      
