version: 2
orbs: 
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs: 
  build_container:
    machine: # executor typ
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Build the Docker image
          working_directory: .
          command: | 
            docker build -t bipen2001/docker-react -f Dockerfile.dev .  

      - run:
          name: run tests
          working_directory: .
          command: | 
            sudo docker run -e CI=True  bipen2001/docker-react npm run test -- --coverage     
  deploy-me:
      docker:
        - image: cimg/python:3.10
      steps:
        - checkout
        - run: pip3 --version
        - run:
            working_directory: /
            name: installing ebcli
            command: pip3 install awsebcli --upgrade --user
        - run: eb --version
        - run:
            name: deploying with awsebcli
            command: eb deploy ReactDocker           
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_container
      - deploy-me
     
