name: react_docker_ci_cd
on:
  push:
    branches: [main]
  pull_request:
     

  workflow_dispatch:

jobs:
  build-container:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      working-directory: main
      run: docker build -t bipen2001/docker-react -f Dockerfile.dev .

    - name: run tests
      working-directory: main
      run: sudo docker run -e CI=True  bipen2001/docker-react npm run test -- --coverage 
   

 