name: react_docker_ci_cd
on:
  push:
    branches: [main]
  pull_request:
     

  workflow_dispatch:

jobs:
  build-container:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      working-directory: main
      run: docker build -t bipen2001/docker-react -f Dockerfile .

    - name: run tests
      working-directory: main
      run: sudo docker run -e CI=True  bipen2001/docker-react npm run test -- --coverage

    - name: Generate deployment package
      run: zip -r main.zip ./main -x '*node_modules*'  

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'


    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: dockerReact
        environment_name: Dockerreact-env-1
        version_label: Sample Application
        region: us-east-1
        deployment_package: main.zip  
        existing_bucket_name: elasticbeanstalk-us-east-1-404725089058
        
        # use_existing_version_if_available: true   

    - name: Deployed!
      run: echo App deployed to ELB